### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Specthra** [XZot1K/SimplePortals#27]
[15:08:03 ERROR]: Could not pass event PlayerRespawnEvent to SimplePortals v1.6.4
java.lang.IllegalArgumentException: Respawn location can not be null
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-564]
at org.bukkit.event.player.PlayerRespawnEvent.setRespawnLocation(PlayerRespawnEvent.java:46) ~[patched_1.16.5.jar:git-Paper-564]
at xzot1k.plugins.sp.core.Listeners.onPortal(Listeners.java:141) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor526.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-564]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-564]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-564]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:913) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:811) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2443) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-564]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-564]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Screenshots & Other Media**
![image](https://user-images.githubusercontent.com/77130187/112211782-34d64d80-8bea-11eb-97ca-e83ecbf2b16a.png)

**Server Information (Please fill in the information below):**
 - Version: paper-1.16.5-564.jar
 - Plugins:
![image](https://user-images.githubusercontent.com/77130187/112211549-06f10900-8bea-11eb-9f4a-07491b4f6504.png)

**Comment by bunnkywhat** [comment]
I am having the same problem, just updated SimplePortals yesterday: https://pastebin.com/s6ibZjyJ

![Screenshot 2021-03-29 063744](https://user-images.githubusercontent.com/6545569/112825042-48a20980-9059-11eb-923e-de26ded39b88.png)

Server Information
Paper version git-Paper-570 (MC: 1.16.5)

**Comment by XZot1K** [comment]
> 
> 
> [15:08:03 ERROR]: Could not pass event PlayerRespawnEvent to SimplePortals v1.6.4
> java.lang.IllegalArgumentException: Respawn location can not be null
> at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.5.jar:git-Paper-564]
> at org.bukkit.event.player.PlayerRespawnEvent.setRespawnLocation(PlayerRespawnEvent.java:46) ~[patched_1.16.5.jar:git-Paper-564]
> at xzot1k.plugins.sp.core.Listeners.onPortal(Listeners.java:141) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor526.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-564]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-564]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-564]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:913) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:811) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2443) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-564]
> at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-564]
> at java.lang.Thread.run(Thread.java:834) [?:?]
> 
> **Screenshots & Other Media**
> ![image](https://user-images.githubusercontent.com/77130187/112211782-34d64d80-8bea-11eb-97ca-e83ecbf2b16a.png)
> 
> **Server Information (Please fill in the information below):**
> 
>     * Version: paper-1.16.5-564.jar
> 
>     * Plugins:
>       ![image](https://user-images.githubusercontent.com/77130187/112211549-06f10900-8bea-11eb-9f4a-07491b4f6504.png)

Resolved it by adjusting a check that didn't make it into the final build redownloading 1.6.4 from https://github.com/XZot1K/SimplePortals/releases/tag/1.6.4 will resolve it!
