### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by shiqutong** [XZot1K/SimplePortals#29]
[11:08:56] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to SimplePortals v1.5.3
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.GHAST_CHARGE
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.bukkit.Sound.valueOf(Sound.java:13) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at xzot1k.plugins.sp.api.objects.Portal.performAction(Portal.java:229) ~[?:?]
	at xzot1k.plugins.sp.core.Listeners.onMove(Listeners.java:155) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1440) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.network.protocol.game.PacketPlayInFlying.a(PacketPlayInFlying.java:114) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(PacketPlayInFlying.java:42) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"321ddfe"]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by DamienVG99** [comment]
Same problem!

**Comment by XZot1K** [comment]
> No enum constant org.bukkit.Sound.GHAST_CHARGE

In the config.yml the value "GHAST_CHARGE" would need to be changed to one in your version of MC. The plugin was unable to find the sound or detect it for the correct version. This can be set to "" as a quick fix.
