### ISSUE TITLE
[BUG] org.bukkit.plugin.java.JavaPlugin not found

### ISSUE THREAD

**Issue by AirOne01** [XZot1K/SimplePortals#39]
**Describe the bug**
```
01:43:26 [WARNING] Error loading plugin SimplePortals
mc-proxy        | java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
mc-proxy        |     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
mc-proxy        |     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
mc-proxy        |     at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
mc-proxy        |     at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
mc-proxy        |     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
mc-proxy        |     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
mc-proxy        |     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
mc-proxy        |     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
mc-proxy        |     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
mc-proxy        |     at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
mc-proxy        |     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
mc-proxy        |     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
mc-proxy        |     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
mc-proxy        | Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
mc-proxy        |     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
mc-proxy        |     at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
mc-proxy        |     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
mc-proxy        |     ... 13 more
```
This error message is the only thing remotely telling me what happened

**To Reproduce**
Steps to reproduce the bug:
- Launch bungee with the plugin

**Expected behavior**
Plugin loads

**Server Information (Please fill in the information below):**
 - Version: Bungeecord latest build
 - Plugins: None

**Additional context**
Minecraft server on which bungee is connecting is Paper version `git-Paper-127`

**Comment by XZot1K** [comment]
This plugin only runs on Spigot/Bukkit instances. It does not need to be installed on the BungeeCord proxy.
