### ISSUE TITLE
Simple portals 1.3 can not be used with Latest build spigot 1.13.2

### ISSUE THREAD

**Issue by mamireimu** [XZot1K/SimplePortals#4]
Latest build spigot 1.13.2 does not load with the following error at startup

> [04:40:59] [Server thread/ERROR]: Could not load 'plugins\SimplePortals.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.14
	at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:332) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by XZot1K** [comment]
This has already been addressed in an upcoming update.

**Comment by XZot1K** [comment]
This is issue was closed due to the new update being release on the main page!
